# Generated by Django 3.0.8 on 2020-07-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='Isbn',
            field=models.CharField(default='', max_length=50, verbose_name='Isbn'),
        ),
    ]
